name: Auto Tag & Release

on:
  workflow_dispatch:

jobs:
  autotag-and-release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            new_tag="v$major.$minor.$((patch+1))"
          else
            new_tag="v1.0.0"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "NEW_TAG=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ env.new_tag }}
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} ${{ env.new_tag }}

      - name: Download Linux 7z artifact
        uses: actions/download-artifact@v4
        with:
          name: bin2cpp-linux-${{ env.new_tag }}.7z
          path: ./
      - name: Download Linux zip artifact
        uses: actions/download-artifact@v4
        with:
          name: bin2cpp-linux-${{ env.new_tag }}.zip
          path: ./
      - name: Download Linux tar artifact
        uses: actions/download-artifact@v4
        with:
          name: bin2cpp-linux-${{ env.new_tag }}.tar
          path: ./
      - name: Download Windows 7z artifact
        uses: actions/download-artifact@v4
        with:
          name: bin2cpp-windows-${{ env.new_tag }}.7z
          path: ./
      - name: Download Windows zip artifact
        uses: actions/download-artifact@v4
        with:
          name: bin2cpp-windows-${{ env.new_tag }}.zip
          path: ./
      - name: Download Windows tar artifact
        uses: actions/download-artifact@v4
        with:
          name: bin2cpp-windows-${{ env.new_tag }}.tar
          path: ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.new_tag }}
          release_name: Release ${{ env.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Linux 7z Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin2cpp-linux-${{ env.new_tag }}.7z
          asset_name: bin2cpp-linux-${{ env.new_tag }}.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Linux zip Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin2cpp-linux-${{ env.new_tag }}.zip
          asset_name: bin2cpp-linux-${{ env.new_tag }}.zip
          asset_content_type: application/zip

      - name: Upload Linux tar Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin2cpp-linux-${{ env.new_tag }}.tar
          asset_name: bin2cpp-linux-${{ env.new_tag }}.tar
          asset_content_type: application/x-tar

      - name: Upload Windows 7z Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin2cpp-windows-${{ env.new_tag }}.7z
          asset_name: bin2cpp-windows-${{ env.new_tag }}.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Windows zip Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin2cpp-windows-${{ env.new_tag }}.zip
          asset_name: bin2cpp-windows-${{ env.new_tag }}.zip
          asset_content_type: application/zip

      - name: Upload Windows tar Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin2cpp-windows-${{ env.new_tag }}.tar
          asset_name: bin2cpp-windows-${{ env.new_tag }}.tar
          asset_content_type: application/x-tar